# Generated by Django 3.2.6 on 2021-08-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210824_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(related_name='post_images', to='main.Image'),
        ),
    ]
