# Generated by Django 3.2.6 on 2021-08-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(null=True, to='main.Image'),
        ),
    ]
