# Generated by Django 3.2.6 on 2021-08-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_post_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(blank=True, to='main.Image'),
        ),
    ]
